# Generated by Django 3.0.7 on 2020-10-02 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0032_remove_restaurant_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='имя')),
                ('lastname', models.CharField(blank=True, max_length=50, verbose_name='фамилия')),
                ('phonenumber', models.CharField(max_length=25, verbose_name='телефон')),
                ('address', models.CharField(max_length=100, verbose_name='фамилия')),
            ],
            options={
                'verbose_name': 'заказ на доставку',
                'verbose_name_plural': 'заказы на доставку',
            },
        ),
        migrations.CreateModel(
            name='OrderProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodcartapp.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodcartapp.Product', verbose_name='продукт в заказе')),
            ],
            options={
                'verbose_name': 'товар в заказе',
                'verbose_name_plural': 'товары в заказе',
            },
        ),
    ]
