# Generated by Django 3.0.7 on 2020-10-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0033_order_orderproductitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductitem',
            name='product_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='сумма одного товара'),
        ),
    ]
