# Generated by Django 3.0.7 on 2020-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0034_orderproductitem_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NO', 'Необработанный'), ('YES', 'Обработанный')], default='NO', max_length=3),
        ),
    ]
