# Generated by Django 3.0.7 on 2020-10-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20201010_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Наличными'), ('Card', 'По карте')], default='Неизвестно', max_length=4, verbose_name='способ оплаты'),
        ),
    ]
